services:
  emulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:6901
      - 8000:8000
    environment:
      VNC_RESOLUTION: 960x864
      VNC_VIEW_ONLY: "true"
      ROCKET_ADDRESS: "0.0.0.0"
    volumes:
      - ./.config:/headless/.config
      - ./PokemonRed.zip:/headless/PokemonRed.zip
    command:
      [
        "sh",
        "./startup.sh",
        "./PokemonRed.zip",
        "--fullscreen",
        "--doNotSaveSettings",
        "--preferences.alwaysOnTop=true",
        "--preferences.autoHideMenu=true",
      ]
